server:
  # 端口
  port: 8001

spring:
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password: 123456

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: satoken
  # OAuth2.0 配置
  oauth2:
    is-code: true
    is-implicit: true
    is-password: true
    is-client: true
